version: '3.2'

services:
    traefik:
        image: traefik:v1.7-alpine
        restart: always
        command: --api --api.entrypoint=traefik --api.dashboard=true --docker --docker.domain=dev --defaultEntryPoints='http' --entryPoints='Name:http Address::80'
                --logLevel=${TRAEFIK_LOG_LEVEL}
        labels:
            - "traefik.backend=traefik"
            - 'traefik.port=8080'
            - 'traefik.frontend.rule=Host:traefik.docker.localhost'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    portainer:
        restart: always
        image: portainer/portainer
        expose:
            - 9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.backend=portainer"
            - "traefik.frontend.rule=Host:portainer.docker.localhost"
        ports:
            - "9001:9000"
networks:
    default:
        external:
            name: proxy
